import ghible from "./ghible-style kenenisa.png";
// import image from "./image.jpg";
// import image1 from "./image1.jpg";
// import image2 from "./image2.jpg";
// import image3 from "./image3.jpg";
// import image4 from "./image4.jpg";
// import image5 from "./image5.jpg";
// import image6 from "./image6.jpg";
import userImage from "./user.png";
import stepIcon1 from "./step_icon_1.svg";
import stepIcon2 from "./step_icon_2.svg";
import stepIcon3 from "./step_icon_3.svg";
import stepIcon from "./logo_icon.svg";
import catSnow from "./cat_snow.png";
import catFlying from "./cat_flying.png";
import profile1 from "./profile_img_1.png";
import profile2 from "./profile_img_2.png";
import profile3 from "./image.jpg";
import star from "./star_group.png";
import cancel from "./cross_icon.svg";
import lock from "./lock_icon.svg";

export const assets = {
    ghible,
    userImage,
    stepIcon,
    stepIcon1,
    stepIcon2,
    stepIcon3,
    catSnow,
    catFlying,
    profile1,
    profile2,
    profile3,
    star,
    cancel,
    lock,
}



export const stepsData = [
    {
        icon: assets.stepIcon,
        title: 'Describe your vission',
        description: 'Type a phrase, sentance, or pharagraph that describe the image you want to create', 
    },
    {
        icon: assets.stepIcon1,
        title: 'Watch the magic happen',
        description: 'Type a phrase, sentance, or pharagraph that describe the image you want to create', 
    },
    {
        icon: assets.stepIcon3,
        title: 'Download the Image generated by AI',
        description: 'Type a phrase, sentance, or pharagraph that describe the image you want to create', 
    },
    {
        icon: assets.stepIcon2,
        title: 'Share the Image if you want',
        description: 'Type a phrase, sentance, or pharagraph that describe the image you want to create', 
    }
];

export const plans = [
    {
        id: 'Basic',
        price: 5,
        description: 'Get 10 credits for $5',
        credits: 10,
    },
    {
        id: 'Standard',
        price: 10,
        description: 'Get 25 credits for $10',
        credits: 25,
    },
    {
        id: 'Premium',
        price: 20,
        description: 'Get 60 credits for $20',
        credits: 60,
    }
];

export const testimony = [
    {
        image: assets.profile1,
        name: 'John Doe',
        role: 'Designer',
        star: '⭐⭐⭐⭐⭐',
        comment: 'PixAi has transformed my design process. I can generate unique images in seconds, saving me hours of work. Highly recommend!'
    },
    {
        image: assets.profile2,
        name: 'Jane Smith',
        role: 'Developer',
        star: '⭐⭐⭐⭐⭐',
        comment: 'The AI image generation is a game changer! I can quickly prototype ideas and share them with my team.'
    },  
    {
        image: assets.profile1,
        name: 'Alice Johnson',
        role: 'Marketer',
        star: '⭐⭐⭐⭐⭐',
        comment: 'PixAi is a must-have tool for any marketer! It saves me so much time and allows me to experiment with different ideas, making my marketing materials stand out from the competition.'
    }
]

 export const Data = [
    {
        one: "The platform is intuitive and the quality of the generated images consistently exceeds my expectations. It has become an essential tool in my creative workflow, allowing me to experiment and iterate on ideas more efficiently than ever before.",
        two: "The intuitive interface and fast results have made it an essential part of our workflow, helping us bring creative concepts to life faster than ever before.",
        three: "I love how easy it is to create stunning visuals for my campaigns. PixAi is a must-have tool for any marketer! It saves me so much time and allows me to experiment with different ideas, making my marketing materials stand out from the competition.",
    }
]