import { assets } from "../assets/assets";
import { motion } from "motion/react";

const Hero = () => {
  return (
    <motion.section className="flex flex-col items-center justify-center px-4 py-10 text-center"
      initial={{opacity:0.2, y:100}}
      transition={{duration:1}}
      whileInView={{opacity:1, y:0}}
      viewport={{once:true}}
      >
      <h1 className="text-3xl text-amber-100 sm:text-4xl font-bold mb-4 dark:text-gray-200">
        Turn Your Imagination Into <span className="text-indigo-600">AI Images</span>
      </h1>
      <p className="text-lg text-gray-100 dark:text-gray-300 mb-12 max-w-2xl">
        Describe anything you can think of and let AI bring it to life in stunning visuals.
      </p>

      <div className="grid md:grid-cols-2 gap-10 max-w-4xl w-full items-center">
        <div className="w-full">
          <img
            src={assets.catSnow}
            alt="A cat in the snow generated by AI"
            className="rounded-xl shadow-lg w-full object-cover"
          />
        </div>

        <div className="text-left space-y-6">
          <h3 className="text-2xl font-semibold text-gray-300 dark:text-gray-200">
            Meet <span className="text-indigo-600 font-bold">PixAi</span>: Your AI-Powered Image Generator
          </h3>
          <p className="text-gray-400 dark:text-gray-300">
            With just a few words, you can create unique and high-quality visuals for any idea—
            from product shots to fantasy characters, abstract art, and more.
          </p>
          <p className="text-gray-400 dark:text-gray-300">
            Whether you're a designer, marketer, or just exploring your creativity, PixAi gives you
            the power to visualize anything instantly. Type a prompt, and let the magic happen.
          </p>
        </div>
      </div>
    </motion.section>
  );
};

export default Hero;
